name: Reusable - Bump Version

on:
  workflow_call:
    inputs:
      bump:
        required: false
        type: string
        default: patch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version ${{ inputs.bump }} --no-git-tag-version
          git add package*.json
          git commit -m "chore: bump version"
          git push

      - name: Create tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag "v$VERSION"
          git push origin "v$VERSION"
